refactor: use printf instead of echo

diff --git a/cozydot b/cozydot
--- a/cozydot
+++ b/cozydot
@@ -11,30 +11,29 @@ DISTRO="" UPSTREAM_DISTRO="" DESKTOP_ENVIRONMENT=""
 
 # Set text colours if supported.
 # Arguments:
-#   colours enabled, a boolean
+#   $1: boolean indicating if colours is enabled
 colours() {
   NC="" BOLD="" RED="" GREEN="" YELLOW="" BLUE="" MAGENTA="" CYAN=""
-  cozydot_txt="cozydot"
-  if [[ "$(tput colors)" -ge 8 ]] && [[ $1 == true ]]; then
-    NC="$(tput sgr0)" # text reset (select graphic representation default)
-    BOLD="$(tput bold)"
-    RED="$(tput setaf 1)"       # red
-    GREEN="$(tput setaf 2)"     # green
-    YELLOW="$(tput setaf 3)"    # yellow
-    BLUE="$(tput setaf 4)"      # blue
-    MAGENTA="$(tput setaf 5)"   # magenta
-    CYAN="$(tput setaf 6)"      # cyan
-    cozydot_txt="${RED}c${YELLOW}o${GREEN}z${CYAN}y${BLUE}d${MAGENTA}o${RED}t${NC}"
+  if [[ $(tput colors) -ge 8 ]] && [[ $1 == true ]]; then
+    NC=$(tput sgr0) # text reset (select graphic representation default)
+    BOLD=$(tput bold)
+    RED=$(tput setaf 1)
+    GREEN=$(tput setaf 2)
+    YELLOW=$(tput setaf 3)
+    BLUE=$(tput setaf 4)
+    MAGENTA=$(tput setaf 5)
+    CYAN=$(tput setaf 6)
   fi
+  cozydot_txt="${RED}c${YELLOW}o${GREEN}z${CYAN}y${BLUE}d${MAGENTA}o${RED}t${NC}"
 }
 
-_info_msg() { echo "${BOLD}${BLUE}Info:${NC} $1"; }
+_info_msg() { printf "%s\n" "${BOLD}${BLUE}Info:${NC} $1"; }
 
-_success_msg() { echo "${BOLD}${GREEN}Success:${NC} $1"; }
+_success_msg() { printf "%s\n" "${BOLD}${GREEN}Success:${NC} $1"; }
 
-_warning_msg() { echo "${BOLD}${YELLOW}Warning:${NC} $1"; }
+_warning_msg() { printf "%s\n" "${BOLD}${YELLOW}Warning:${NC} $1"; }
 
-_error_msg() { echo "${BOLD}${RED}Error:${NC} $1" && exit 1; }
+_error_msg() { printf "%s\n" "${BOLD}${RED}Error:${NC} $1" && exit 1; }
 
 _usage() {
   cat <<EOF
@@ -76,7 +75,7 @@ EOF
 
 # Use config specified in configs directory.
 # Arguments:
-#   name of config yaml file
+#   $1: name of config yaml file
 set_config() {
   CONFIG="$(dirname "$(realpath "$0")")/configs/$1.yaml"
   if [[ ! -f $CONFIG ]]; then
@@ -91,13 +90,13 @@ list_configs() {
     find "$(dirname "$(realpath "$0")")/configs" -type f \
       | awk -F '[/.]' '{print $(NF-1)}'
   )
-  echo "${YELLOW}Available configs:${NC}"
+  printf "%s\n" "${YELLOW}Available configs:${NC}"
   for config in "${configs[@]}"; do
-    echo "  ${GREEN}$config${NC}: $(yq '.metadata.description' "$(dirname "$(realpath "$0")")/configs/$config.yaml")"
+    printf "%s\n" "  ${GREEN}$config${NC}: $(yq '.metadata.description' "$(dirname "$(realpath "$0")")/configs/$config.yaml")"
   done
 }
 
-get_version() { echo "$cozydot_txt $VERSION" && exit; }
+get_version() { printf "%s\n" "$cozydot_txt $VERSION" && exit; }
 
 # ----- SET GLOBAL VARIABLES -----
 
@@ -157,7 +156,7 @@ _set_global_var() {
 
 # Downloads / updates golang.
 # Arguments:
-#   go version. must be either "latest" or <major>.<minor>.<patch>
+#   $1: go version. must be either "latest" or <major>.<minor>.<patch>
 _dl_golang() {
   if [ -z "${1-}" ]; then _error_msg "no value supplied to _dl_golang"; fi
   local latest_go=$1
@@ -179,7 +178,7 @@ _dl_golang() {
 
 # Downloads / updates Node via nvm. Requires nvm to be installed.
 # Arguments:
-#   node version. format must either be "latest" | <major>[.<minor>[.<patch>]]
+#   $1: node version. format must either be "latest" | <major>[.<minor>[.<patch>]]
 _dl_node() {
   if [ -z "${1-}" ]; then _error_msg "no value supplied to _dl_node"; fi
   if ! command -v nvm &>/dev/null; then
@@ -355,9 +354,11 @@ EOF
     fi
 
     # install latest python version if pyenv python version is not latest.
-    local latest_py=$(pyenv latest -k "$(yq '.check.python.version' "$CONFIG")")
+    local latest_py
     if [[ $(yq '.check.python.version' "$CONFIG") == "latest" ]]; then
       latest_py=$(pyenv latest -k 3)
+    else
+      latest_py=$(pyenv latest -k "$(yq '.check.python.version' "$CONFIG")")
     fi
     if [[ $(pyenv version-name) != "$latest_py" ]]; then
       # install if latest ver is not in system (ie not previously installed)
@@ -935,8 +936,7 @@ EOF
 # ----- MAIN -----
 
 main() {
-  # PRINT FUNCTIONS
-  colours true
+  colours true # PRINT FUNCTIONS
 
   # Make this script an executable by creating symlink to /usr/local/bin.
   # script path must be ~/.cozydot/cozydot for standardisation
@@ -966,10 +966,7 @@ main() {
 
   while [[ $# -gt 0 ]]; do
     case $1 in
-      -h | --help)
-        _usage
-        exit 0
-        ;;
+      -h | --help) _usage && exit ;;
       # OPTIONS
       -n | --no-colour) colours false ;;
       -c | --config)
